version: "3.9"
services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    networks:
      - coordinate-resolver-network

  coordinate-resolver:
    container_name: coordinate-resolver
    image: knvelasquez/coordinateresolver:v1.1
    environment:
      # Sets default value 8082 if SPRING_BOOT_PORT is not defined
      - SPRING_BOOT_PORT=${SPRING_BOOT_PORT:-8084}
    ports:
      # Map default value 8082 if SPRING_BOOT_PORT is not defined
      - ${SPRING_BOOT_PORT:-8084}:${SPRING_BOOT_PORT:-8084}
    networks:
      - coordinate-resolver-network
    build:
      context: ./
      dockerfile: Dockerfile

networks:
  coordinate-resolver-network:
    driver: bridge

#set custom port
#SPRING_BOOT_PORT=8181 docker-compose build
#SPRING_BOOT_PORT=8181 docker-compose push
#SPRING_BOOT_PORT=8181 docker-compose up

